services:
  database:
    image: postgres:12
    ports:
      - "5432:5432"

    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-docsy}

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
