services:
  database:
    extends:
      file: common/database.yaml
      service: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  storage:
    image: nginx:alpine
    ports:
      - "9090:80"
    volumes:
      - ./storage/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - storage_data:/data:ro
    restart: unless-stopped

    # extends:
    #   file: common/storage.yaml
    #   service: storage
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"
    # environment:
    #   MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
    #   MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-changeme}
    # volumes:
    #   - db_data:/var/lib/postgresql/data
volumes:
  db_data:
  storage_data:
